# Introduction {-}

In today’s fiercely competitive business environment, companies started to realize the value not only of attractive new customers, but also of keeping the current ones. In today’s market, where consumers have a wide range of services providers to choose from, customers acquisition is frequently expensive and challenging (Van den Poel, 2004).  Therefore, it has become crucial for service-oriented businesses to analyse and reduce client churn. It has been demonstrated that service providers can benefit in several of ways by minimizing client churn. First, it enables one stay focused on meeting the needs of current clients rather than of constantly seeking out new, potentially risky clients. Additionally, because a solid understanding of their preferences has been developed, long-term consumers are typically less costly. At last, losing clients results in lower sales as well as a bad reputation among prospective (Lazarov, V., & Capota, M., 2007).

For these reasons, business have developed Customer Relationship Management (CRM) tools aiming at classifying and predicting customer retention, developing retaining customers tasks in order to maximise their profitability. Churn detection is a crucial focus point for many sectors; this report, in particular, presents the case of a museum association.

The goal of this Project is to provide an analysis about the museum card holders, trying to understand what are the common characteristics among those who renew their subscription and those who do not. The report will consist of several phases. First a descriptive phase in which we will try to understand what are the personal, geographic and behavioural characteristics of all the association's customers, then the analysis will focus on understanding what are the characteristics of customers who tend not to renew their subscription. Next, models for classifying and predicting the probability of churn will be built and evaluated. Finally, the report will answer an economics problem in which the goal is to optimize a marketing campaign aimed at contacting the right customers so that they do not cancel their subscriptions.
\newpage