# Conclusion {-}

In conclusion, this project represents a critically important initiative for the association. Through a deep analysis of museum customers data, we have provided a clear view of customers, the characteristics influencing churn and propose optimal marketing strategies for maximising profits. 

First, we focused on understanding who are museum cardholders, where they live and how they behave from an economic perspective. From a preliminary descriptive analysis, our clients represent a diverse range of individuals, with a little predominance of female clients. The most common age group among them is between 40 and 70 years old. Most of our customers reside in the association region, particularly in the same municipality, where the museums under analysis are located. Our customers mainly make their purchases at information points, museums, and corporate leisure associations.

Throughout data analysis, we examined various variables to identify the characteristics that most influence the likelihood of churn among our museum subscribers. Some significant trends clearly emerge. First, considering age customers who have churned are on average older than those who have renewed their membership. In addition, the frequency of museum visits seems to play a crucial role; those who have made fewer visits have a higher probability of churn. Noteworthy, new customers tend to renew their memberships to a greater extent than existing customers. Finally, geographic analysis reveals significant differences in the likelihood of churn across regions, underscoring the importance of considering geographic context when planning customer retention strategies. In addition, a more analytical approach has been used. After setting up a logistic regression age, visit frequency, subscription history, gender, time since last visit, and amount spent were revealed as the key variables influencing the probability of churn among museum subscribers. These factors will guide the development of targeted retention strategies and predictive models to maximize profits in future marketing campaigns.

Finally, by building predictive models, we have been able to accurately estimate the probability of our customers' churn. These models turned out to be crucial in defining an optimal marketing strategy. Using these tools, we have been able to identify the ideal combination of customers to contact, either through phone calls or email, with the goal of maximizing profits while keeping costs within the established budget. This approach allows us to maintain a high degree of efficiency and focus resources on a targeted way, improving customer retention and optimizing the success of future marketing campaigns.
\newpage